### ISSUE TITLE
No image 

### ISSUE THREAD

**Issue by CxcCoding** [emrekose26/RecordButton#1]
Error:(18, 25) No resource found that matches the given name (at 'recordIcon' with value '@drawable/ic_keyboard_voice_white_36dp').

**Comment by CxcCoding** [comment]
ObjectAnimator animator = ObjectAnimator.ofFloat(this, "progress", currentMiliSecond, maxMilisecond);

Did not find SetProgress

**Comment by kido9797** [comment]
I have the same issue.
