### ISSUE TITLE
Rewrite with Kotlin

### ISSUE THREAD

**Issue by emrekose26** [emrekose26/RecordButton#10]

**Comment by hensou** [comment]
Hi @emrekose26! I don't have that much experience with Android Development, but I think I can help you with that if it's okay.

**Comment by emrekose26** [comment]
Hi @hensou. I'll be waiting for your PR.

**Comment by cebthedev** [comment]
Hi @emrekose26  I have experience in Kotlin and Android Development. I can help if you let me.

**Comment by emrekose26** [comment]
Hi @PinkFLoyd92 @hensou  
Of course. You can contribute this repo. I'll be waiting for your PR.
