### ISSUE TITLE
Feature Idea: Cancel recording gesture 

### ISSUE THREAD

**Issue by yesidlazaro** [emrekose26/RecordButton#2]
First at all thanks for share your library, 
i am looking to use it in one of my project but i was wondering if is possible have a gesture to cancel the recording ? something like "swipe down" to cancel".

thanks again.

**Comment by emrekose26** [comment]
Hi @yesidlazaro 
Yes it is possible. There is `ACTION_UP`gestures for this. But there is no listener method for cancel like `onCancel()`. I will try to add to future commits this feature

**Comment by yesidlazaro** [comment]
that was fast! thanks @emrekose26 !
