### ISSUE TITLE
Importing via jitpack.io doesn't work

### ISSUE THREAD

**Issue by daruuro** [emrekose26/RecordButton#4]
Importing via jitpack.io doesn't work. Looked at the jitpack.io website, and there are error logs available there. Other jitpack packages that I've imported into my project succesfully don't show error logs on the jitpack website.
https://jitpack.io/com/github/emrekose26/RecordButton/1.2.1/build.log

**Comment by daruuro** [comment]
This still doesn't work. Any comment on the issue?

**Comment by emrekose26** [comment]
Hi @yaabdalla 
I try to figure out reason of this issue. Also, I've released new version but still does not work. If you have any suggestion for this let me know with comment.

**Comment by emrekose26** [comment]
You can use like
`compile 'com.github.emrekose26:RecordButton:-SNAPSHOT'`
for now

**Comment by lekeCoder** [comment]
hello @emrekose26 the snapshot is not working. Please help

**Comment by emrekose26** [comment]
@yaabdalla @lekeCoder
Now you can use stable version 
`compile 'com.github.emrekose26:RecordButton:1.2.4'`
