### ISSUE TITLE
How does it work? 

### ISSUE THREAD

**Issue by lekeCoder** [emrekose26/RecordButton#6]
I followed the tutorial to implement this library but each time l click on the RecordButton, onRecord() method is called followed by onRecordCancel() method almost immediately. No recording takes place despite my defined recording method. 
Please what am l missing? It does not even show the progressbar  progress. 

please help out

**Comment by emrekose26** [comment]
Library provides limited recording like 10ms, 30 ms or whatever you want (like Snapchat, Instagram). It can't continuous recording. 
When you clicked(long click) on the button it triggers `onRecord()` method. if time does not complete it triggers `onRecordCancel()` method.
