### ISSUE TITLE
importing in dependency not working

### ISSUE THREAD

**Issue by netoolii** [emrekose26/RecordButton#8]
Error:(35, 13) Failed to resolve: com.github.emrekose26:RecordButton:1.2.4

i paste this code in dependencies, but show this message arrive.

compile 'com.github.emrekose26:RecordButton:1.2.4'

**Comment by emrekose26** [comment]
Have you added the following lines in your `build.gradle` (project) 

    allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
